### ISSUE TITLE
Taser still does not work...

### ISSUE THREAD

**Issue by ThatGuyRage** [RPFramework/RPFramework#19]
Every thing works so far but the taser it kills or make the player bleed out.

**Comment by superihippo** [comment]
Scheduled for mp testing

**Comment by kerkkoh** [comment]
Taser will be disabled with the new release since it never worked and is fairly clunky anyways. Will be replaced in the future if someone takes the time to make one that is compatible with the medical system.

**Comment by theflyingjets** [comment]
I have fixed the Taser! Where would you like me to upload the Taser modules.

**Comment by kerkkoh** [comment]
Dropbox works or you can just make a new public repository on github which might be even better.

**Comment by ThatGuyRage** [comment]
We still have a bug we are fixing with it atm when you take any damage you get tased

**Comment by kerkkoh** [comment]
Make sure that it works with the medical module and that it's tested in MP. Once you are done, do either a pull request with the new module included to the newest RPFramework version or just give me a link to it here.

**Comment by kerkkoh** [comment]
@theflyingjets Any update on this?

**Comment by ThatGuyRage** [comment]
@superihippo Its been a busy few weeks for Jets and I but we hope we can get it done this weekend.

**Comment by kerkkoh** [comment]
Copy that. No worries. I already caught Jets via twitter so it's fine!

**Comment by theflyingjets** [comment]
Taser has been fixed and will be in next update!
